const data = [
  {
    id: 1,
    name: "New Balance 530 'White Silver Blue'",
    img: "img/1.jpg",
    price: 150,
  },
  {
    id: 2,
    name: "Nike Air Max Plus 'Summit' White Pink",
    img: "img/2.jpg",
    price: 190,
  },
  {
    id: 3,
    name: "New Balance 327 'Phantom Black'",
    img: "img/3.jpg",
    price: 250,
  },
  {
    id: 4,
    name: "New Balance 327 'Grey Matter'",
    img: "img/4.jpg",
    price: 175,
  },
  {
    id: 5,
    name: "Jordan Jumpman Jack TR Travis Scott 'Sail'",
    img: "img/5.jpg",
    price: 200,
  },
  {
    id: 6,
    name: "Vans Old Skool Comfy Cush 'Black'",
    img: "img/6.jpg",
    price: 193,
  },
  {
    id: 7,
    name: "Vans Old Skool x Imran Potato 'Black White'",
    img: "img/7.jpg",
    price: 205,
  },
  {
    id: 8,
    name: "Nike Air Max 97 'Neon Mirage'",
    img: "img/8.jpg",
    price: 320,
  },
  {
    id: 9,
    name: "Nike Air Force 1 'Barely Rose'",
    img: "img/9.jpg",
    price: 300,
  },
  {
    id: 10,
    name: "Nike Air Max Plus 'Solar Flare'",
    img: "img/10.jpg",
    price: 400,
  },
  {
    id: 11,
    name: "Jordan 4 Retro 'Desert Clay'",
    img: "img/11.jpg",
    price: 310,
  },
  {
    id: 12,
    name: "Jordan 3 Retro 'Smoke Grey Suede'",
    img: "img/12.jpg",
    price: 200,
  },
  {
    id: 13,
    name: "New Balance 327 'Grey Matter'",
    img: "img/13.jpg",
    price: 190,
  },
  {
    id: 14,
    name: "Vans Slip-On 'Pebble Grey'",
    img: "img/14.jpg",
    price: 200,
  },
  {
    id: 15,
    name: "Adidas Gazelle 'Pebble Pink'",
    img: "img/15.jpg",
    price: 200,
  },
  {
    id: 16,
    name: "Adidas Stan Smith 'Pale Moss'",
    img: "img/16.jpg",
    price: 200,
  },
  {
    id: 17,
    name: "Nike Air Max 90 'Terracotta Dawn'",
    img: "img/17.jpg",
    price: 200,
  },
  {
    id: 18,
    name: "Jordan 1 Low 'Antique Bone'",
    img: "img/18.jpg",
    price: 200,
  },
  {
    id: 19,
    name: "Vans Old Skool x Something 'Concrete Waves'",
    img: "img/19.jpg",
    price: 200,
  },
]